@host=https://localhost:7206

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Amichai",
    "lastName": "Mantinband",
    "email": "amichai@mantonband.com",
    "password": "eyJhb..hbbQ"
}